version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - flask-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - flask-network

networks:
  flask-network:
